Fix Workflow Parameter, Docker Log Path

diff --git a/.github/workflows/deploy-docker-prod.yml b/.github/workflows/deploy-docker-prod.yml
--- a/.github/workflows/deploy-docker-prod.yml
+++ b/.github/workflows/deploy-docker-prod.yml
@@ -1,28 +1,22 @@
-# name: Deploy Docker Prod
-
-# on:
-#   workflow_dispatch:
-#     inputs:
-#       be_version:
-#         description: '배포할 BE 버전 (예: 1.2.3)'
-#         required: true
-#       be_slot:
-#         description: 'BE 슬롯 선택 (예: blue, green)'
-#         required: true
-#         default: 'green'
-      # fe_version:
-      #   description: '배포할 FE 버전 (예: 1.2.3)'
-      #   required: true
-      # fe_slot:
-      #   description: 'FE 슬롯 선택 (예: blue, green)'
-      #   required: true
-      #   default: 'green'
-name: Deploy Docker Prod (Slot Temporary Hardcoded)
+name: Deploy Docker Prod
 
 on:
-  push:
-    branches:
-      - feat/docker
+  workflow_dispatch:
+    inputs:
+      be_version:
+        description: '배포할 BE 버전 (예: 1.2.3)'
+        required: true
+      be_slot:
+        description: 'BE 슬롯 선택 (예: blue, green)'
+        required: true
+        default: 'green'
+      fe_version:
+        description: '배포할 FE 버전 (예: 1.2.3)'
+        required: true
+      fe_slot:
+        description: 'FE 슬롯 선택 (예: blue, green)'
+        required: true
+        default: 'green'
 
 
 jobs:
@@ -84,18 +78,18 @@ jobs:
 
       # ------------------ FE 업로드 ------------------
 
-      # - name: Download FE artifact from GitHub Release
-      #   run: |
-      #     curl -L -o fe.zip https://github.com/$GH_FE_REPO/releases/download/v${{ steps.vars.outputs.fe_version }}/frontend-prod-build.zip
-      #     unzip -o fe.zip -d fe-dist
+      - name: Download FE artifact from GitHub Release
+        run: |
+          curl -L -o fe.zip https://github.com/$GH_FE_REPO/releases/download/v${{ steps.vars.outputs.fe_version }}/frontend-prod-build.zip
+          unzip -o fe.zip -d fe-dist
 
-      # - name: Upload FE to S3
-      #   env:
-      #     AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
-      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
-      #     AWS_DEFAULT_REGION: ap-northeast-2
-      #   run: |
-      #     aws s3 sync fe-dist/ s3://onthe-top/frontend/prod/${{ steps.vars.outputs.fe_slot }} --delete
+      - name: Upload FE to S3
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
+          AWS_DEFAULT_REGION: ap-northeast-2
+        run: |
+          aws s3 sync fe-dist/ s3://onthe-top/frontend/prod/${{ steps.vars.outputs.fe_slot }} --delete
 
       # ------------------ BE 배포 ------------------
 
@@ -155,93 +149,93 @@ jobs:
               UserKnownHostsFile /dev/null
           EOF
 
-      # - name: Generate secrets.properties file
-      #   run: |
-      #     mkdir -p ./secrets
-      #     touch ./secrets/secrets.properties
-      #     SECRET_LABELS="backend_shared backend_prod"
+      - name: Generate secrets.properties file
+        run: |
+          mkdir -p ./secrets
+          touch ./secrets/secrets.properties
+          SECRET_LABELS="backend_shared backend_prod"
 
-      #     for LABEL in $SECRET_LABELS; do
-      #       gcloud secrets list --filter="labels.env=$LABEL" --format="value(name)" | while read SECRET_NAME; do
-      #         SECRET_VALUE=$(gcloud secrets versions access latest --secret="$SECRET_NAME")
-      #         IFS='-' read -r SERVICE KEY ENV <<< "$SECRET_NAME"
-      #         echo "${KEY}=${SECRET_VALUE}" >> ./secrets/secrets.properties
-      #       done
-      #     done
+          for LABEL in $SECRET_LABELS; do
+            gcloud secrets list --filter="labels.env=$LABEL" --format="value(name)" | while read SECRET_NAME; do
+              SECRET_VALUE=$(gcloud secrets versions access latest --secret="$SECRET_NAME")
+              IFS='-' read -r SERVICE KEY ENV <<< "$SECRET_NAME"
+              echo "${KEY}=${SECRET_VALUE}" >> ./secrets/secrets.properties
+            done
+          done
 
-      # - name: Upload secrets.properties to server
-      #   run: |
-      #     ssh -F ~/.ssh/config backend-server 'mkdir -p ~/backend'
-      #     scp -F ~/.ssh/config ./secrets/secrets.properties backend-server:/home/ubuntu/backend/secrets.properties
+      - name: Upload secrets.properties to server
+        run: |
+          ssh -F ~/.ssh/config backend-server 'mkdir -p ~/backend'
+          scp -F ~/.ssh/config ./secrets/secrets.properties backend-server:/home/ubuntu/backend/secrets.properties
  
 
-      # - name: Deploy Dcoker Backend via SSH
-      #   env:
-      #     BE_VERSION: ${{ steps.vars.outputs.be_version }}
-      #     BE_SLOT: ${{ steps.vars.outputs.be_slot }}
-      #     BE_PORT: ${{ steps.vars.outputs.be_port }}
-      #   run: |
-      #     echo "▶️ Deploying backend $BE_VERSION on slot $BE_SLOT (port $BE_PORT)..."
-      #     ssh backend-server "BE_VERSION=${BE_VERSION} BE_SLOT=${BE_SLOT} BE_PORT=${BE_PORT} bash -s" <<'EOF'
-      #         set -e
+      - name: Deploy Dcoker Backend via SSH
+        env:
+          BE_VERSION: ${{ steps.vars.outputs.be_version }}
+          BE_SLOT: ${{ steps.vars.outputs.be_slot }}
+          BE_PORT: ${{ steps.vars.outputs.be_port }}
+        run: |
+          echo "▶️ Deploying backend $BE_VERSION on slot $BE_SLOT (port $BE_PORT)..."
+          ssh backend-server "BE_VERSION=${BE_VERSION} BE_SLOT=${BE_SLOT} BE_PORT=${BE_PORT} bash -s" <<'EOF'
+              set -e
 
-      #         # 0. 필수 패키지 설치
-      #         sudo apt update && sudo apt install -y docker.io jq gettext
+              # 0. 필수 패키지 설치
+              sudo apt update && sudo apt install -y docker.io jq gettext
 
-      #         VERSION="$BE_VERSION"
-      #         SLOT="$BE_SLOT"
-      #         PORT="$BE_PORT"
-      #         ENV="prod"
-      #         CONTAINER_NAME="onthetop-backend-${SLOT}"
+              VERSION="$BE_VERSION"
+              SLOT="$BE_SLOT"
+              PORT="$BE_PORT"
+              ENV="prod"
+              CONTAINER_NAME="onthetop-backend-${SLOT}"
 
-      #         # 2. 이전 같은 slot 컨테이너 있다면 제거
-      #         echo "🧹 Cleaning up old container named $CONTAINER_NAME..."
-      #         EXISTING_CONTAINER=$(docker ps -aq --filter "name=^/$CONTAINER_NAME\$" || true)
-      #         if [ -n "$EXISTING_CONTAINER" ]; then
-      #           docker rm -f "$EXISTING_CONTAINER"
-      #         fi
+              # 2. 이전 같은 slot 컨테이너 있다면 제거
+              echo "🧹 Cleaning up old container named $CONTAINER_NAME..."
+              EXISTING_CONTAINER=$(docker ps -aq --filter "name=^/$CONTAINER_NAME\$" || true)
+              if [ -n "$EXISTING_CONTAINER" ]; then
+                docker rm -f "$EXISTING_CONTAINER"
+              fi
 
-      #         # 3. Docker 이미지 pull
-      #         echo " Pulling Docker image luckyprice1103/onthetop-backend:$VERSION"
-      #         docker pull luckyprice1103/onthetop-backend:$VERSION
+              # 3. Docker 이미지 pull
+              echo " Pulling Docker image luckyprice1103/onthetop-backend:$VERSION"
+              docker pull luckyprice1103/onthetop-backend:$VERSION
 
-      #         # 4. Docker 이미지 실행
-      #         echo "🚀 Running backend Docker container on port $PORT..."
-      #         docker run -d \
-      #           --name "$CONTAINER_NAME" \
-      #           -p "$PORT":8080 \
-      #           --memory=512m \
-      #           --cpus=0.5 \
-      #           -v /home/ubuntu/backend/secrets.properties:/app/secrets.properties \
-      #           -v /var/log/onthetop/backend:/logs \
-      #           -e SPRING_PROFILES_ACTIVE="$ENV" \
-      #           luckyprice1103/onthetop-backend:$VERSION \
-      #           --logging.file.path=/logs/backend.log \
-      #           --spring.config.additional-location=file:/app/secrets.properties
+              # 4. Docker 이미지 실행
+              echo " Running backend Docker container on port $PORT..."
+              docker run -d \
+                --name "$CONTAINER_NAME" \
+                -p "$PORT":8080 \
+                --memory=512m \
+                --cpus=0.5 \
+                -v /home/ubuntu/backend/secrets.properties:/app/secrets.properties \
+                -v /var/log/onthetop/backend:/logs \
+                -e SPRING_PROFILES_ACTIVE="$ENV" \
+                luckyprice1103/onthetop-backend:$VERSION \
+                --logging.file.name=/logs/backend.log \
+                --spring.config.additional-location=file:/app/secrets.properties
 
-      #         echo "✅ Backend container is running on port $PORT"
-      #     EOF
+              echo "✅ Backend container is running on port $PORT"
+          EOF
 
-      # - name: Health check
-      #   env:
-      #     BE_PORT: ${{ steps.vars.outputs.be_port }}
-      #   run: |
-      #     echo "🩺 Health check for backend container on port $BE_PORT..."
+      - name: Health check
+        env:
+          BE_PORT: ${{ steps.vars.outputs.be_port }}
+        run: |
+          echo "🩺 Health check for backend container on port $BE_PORT..."
 
-      #     ssh -F ~/.ssh/config backend-server <<EOF
-      #       for i in {1..10}; do
-      #         echo " [$i/10] Waiting for backend health on port $BE_PORT..."
-      #         STATUS=\$(curl -s -o /dev/null -w "%{http_code}" http://localhost:$BE_PORT/api/v1/health || echo "000")
-      #         if [ "\$STATUS" = "200" ]; then
-      #           echo "✅ Health check passed."
-      #           exit 0
-      #         fi
-      #         sleep 10
-      #       done
+          ssh -F ~/.ssh/config backend-server <<EOF
+            for i in {1..10}; do
+              echo " [$i/10] Waiting for backend health on port $BE_PORT..."
+              STATUS=\$(curl -s -o /dev/null -w "%{http_code}" http://localhost:$BE_PORT/api/v1/health || echo "000")
+              if [ "\$STATUS" = "200" ]; then
+                echo "✅ Health check passed."
+                exit 0
+              fi
+              sleep 10
+            done
 
-      #       echo "❌ Health check failed after 10 attempts."
-      #       exit 1
-      #     EOF
+            echo "❌ Health check failed after 10 attempts."
+            exit 1
+          EOF
 
 
       - name: Switch Nginx to new backend slot
@@ -273,43 +267,43 @@ jobs:
           EOF
       # ------------------ CloudFront Origin 변경 및 무효화 ------------------
 
-  # cdn-update:
-  #   needs: deploy
-  #   runs-on: ubuntu-latest
-  #   env:
-  #     AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFRONT_ACCESS_KEY }}
-  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFRONT_SECRET_KEY }}
-  #     AWS_DEFAULT_REGION: ap-northeast-2
-  #     CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
-  #   steps:
-  #     - name: Update CloudFront Origin
-  #       run: |
-  #         SLOT="${{ needs.deploy.outputs.fe_slot }}"
-  #         DIST_ID="$CLOUDFRONT_DISTRIBUTION_ID"
+  cdn-update:
+    needs: deploy
+    runs-on: ubuntu-latest
+    env:
+      AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFRONT_ACCESS_KEY }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFRONT_SECRET_KEY }}
+      AWS_DEFAULT_REGION: ap-northeast-2
+      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
+    steps:
+      - name: Update CloudFront Origin
+        run: |
+          SLOT="${{ needs.deploy.outputs.fe_slot }}"
+          DIST_ID="$CLOUDFRONT_DISTRIBUTION_ID"
 
-  #         # 원본 전체 구성 받아오기
-  #         aws cloudfront get-distribution-config --id $DIST_ID > raw.json
+          # 원본 전체 구성 받아오기
+          aws cloudfront get-distribution-config --id $DIST_ID > raw.json
 
-  #         # ETag 추출
-  #         ETAG=$(jq -r '.ETag' raw.json)
+          # ETag 추출
+          ETAG=$(jq -r '.ETag' raw.json)
 
-  #         # DistributionConfig만 추출
-  #         jq '.DistributionConfig' raw.json > config-only.json
+          # DistributionConfig만 추출
+          jq '.DistributionConfig' raw.json > config-only.json
 
-  #         # OriginPath 수정
-  #         jq --arg SLOT "$SLOT" \
-  #           '.Origins.Items[0].OriginPath = "/frontend/prod/\($SLOT)"' \
-  #           config-only.json > updated-config.json
+          # OriginPath 수정
+          jq --arg SLOT "$SLOT" \
+            '.Origins.Items[0].OriginPath = "/frontend/prod/\($SLOT)"' \
+            config-only.json > updated-config.json
 
-  #         # 업데이트 적용
-  #         aws cloudfront update-distribution \
-  #           --id $DIST_ID \
-  #           --if-match $ETAG \
-  #           --distribution-config file://updated-config.json
+          # 업데이트 적용
+          aws cloudfront update-distribution \
+            --id $DIST_ID \
+            --if-match $ETAG \
+            --distribution-config file://updated-config.json
 
-  #     - name: Invalidate CloudFront cache
-  #       run: |
-  #         SLOT="${{ needs.deploy.outputs.fe_slot }}"
-  #         aws cloudfront create-invalidation \
-  #           --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" \
-  #           --paths "/" "/index.html" "/assets/*.js" "/assets/*.css"
+      - name: Invalidate CloudFront cache
+        run: |
+          SLOT="${{ needs.deploy.outputs.fe_slot }}"
+          aws cloudfront create-invalidation \
+            --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" \
+            --paths "/" "/index.html" "/assets/*.js" "/assets/*.css"
